
name: Build VS Code extension

# When changes are pushed to main, this workflow will:
#  @TODO: fill out!

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: 
      - main

jobs:
  build-vsix:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 16

      # - uses: actions/checkout@v4

      # - name: Install dependencies
      #   run: npm install

      # - name: Install vsce
      #   run: npm i -g @vscode/vsce

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: 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

      - name: Echo result 1
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: echo doesnth have changesets ${{steps.changesets.outputs.hasChangesets}}

      - name: Echo result 2
        if: steps.changesets.outputs.hasChangesets == 'true'
        run: echo has changesets ${{steps.changesets.outputs.hasChangesets}}

      - name: Echo result 3
        if: steps.changesets.outputs.hasChangesets != 'true'
        run: echo no results